<div class="flex items-center gap-1 overflow-x-auto border-b border-ink-100 mb-8 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
    <a href="{{ route('admin.dashboard') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.dashboard') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Ringkasan</a>
    <a href="{{ route('admin.stores.index') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.stores.*') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Toko</a>
    <a href="{{ route('admin.products.index') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.products.*') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Moderasi Produk</a>
    <a href="{{ route('admin.categories.index') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.categories.*') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Kategori</a>
    <a href="{{ route('admin.banners.index') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.banners.*') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Banner</a>
    <a href="{{ route('admin.users.index') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.users.*') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Pengguna</a>
    <a href="{{ route('admin.orders.index') }}" class="shrink-0 px-4 py-3 text-sm font-semibold border-b-2 -mb-px transition-colors {{ request()->routeIs('admin.orders.*') ? 'border-clay-500 text-clay-600' : 'border-transparent text-ink-400 hover:text-ink-700' }}">Transaksi</a>
</div>
